### ISSUE TITLE
Boot loop na firmware update met p1-dongle-pro.yaml

### ISSUE THREAD

**Issue by westende** [mhendriks/esphome-p1#1]
Na update van ESPHome firmware middels p1-dongle-pro.yaml komt de P1 dongle Pro in een boot loop.

Door esp32.framework.version te overschrijven krijg ik wel het gewenste resultaat:

```yaml
esp32:
  framework:
    version: 2.0.6
```

**Comment by mhendriks** [comment]
2.0.6 werkt inderdaad ook op de Dongle. Heb testen met de 2.0.3, 2.0.4  en de 2.0.6 gedaan met diverse platform_versies. 2.0.4 geeft problemen en dien je over te slaan.

2.0.3 / 4.4.0 werkt stabiel
2.0.6 / 4.4.0 en 5.x werkt wel maar minder stabiel. De dongle reboot vaak ... Check de uptime in HA de komende tijd om te zien of deze stabiel blijft draaien.

**Comment by westende** [comment]
2.0.6 / 4.4.0 werkt vooralsnog stabiel. Enig idee waarom 2.0.3 / 4.4.0 in een boot loop terecht zou komen?

**Comment by mhendriks** [comment]
goed om te weten.
Mijn ervaringen met 2.0.3 en 4.4.0 zijn juist heel goed.  Waarom dit afwijkend is in jouw situatie snap ik niet helemaal. 
Hoe ziet de totale config er uit onder esp32: ?

**Comment by westende** [comment]
Ik maak nu gebruik van de volgende configuratie:

```yaml
substitutions:
  name: p1-dongle-pro

packages:
  smartstuff.p1_dongle_pro: github://mhendriks/esphome-p1/p1-dongle-pro.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false

esp32:
  framework:
    version: 2.0.6

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
