### ISSUE TITLE
Waterlezer: update to pulse_meter and add device_class

### ISSUE THREAD

**Issue by dewi-ny-je** [mhendriks/esphome-p1#10]
Hi, I think it's worth to update the waterlezer with the improved platform "pulse_meter", see https://esphome.io/components/sensor/pulse_meter.html

Something like (please check!)

```
  - platform: pulse_meter
    pin: 
      number: 5
      mode:
        input: true
        pullup: true #v3.5 aanzetten
    id: watermeter_pulse
    name: "Watermeter flow"
    state_class: measurement
    device_class: "volume_flow_rate"
    update_interval: 1s # does it send a value per second to HA? waste of bandwidth and influxdb storage I tried delta below
    internal_filter: 500ms # at max flow, one pulse every 800ms anyway
    timeout: 1min
    accuracy_decimals: 0
    unit_of_measurement: 'L/min'
    filters:
        - delta: 0 #pass through the value only if something changed, delta ">" 0
        - heartbeat: 60s # at least ping a value every minute
    total:
        name: "Watermeter total"
        state_class: "total_increasing"
        device_class: "water"
        icon: mdi:water
        update_interval: 1s
        unit_of_measurement: L
        accuracy_decimals: 0
        filters:
            - multiply: 0.001
            - delta: 0
            - heartbeat: 60s

api:
  services:
    - service: set_total
      variables:
        new_total: int
      then:
        - pulse_meter.set_total_pulses:
            id: sensor_pulse_meter
            value: !lambda 'return new_total * 1000;' # untested, still waiting for your device to arrive

```

and no globals needed to be updated via lambda (or maybe needed for restoring from flash?)

**Comment by mhendriks** [comment]
thanks for the hints. I tried it before but there was a problem with the total counter when using the pulse_meter. I will try it again with the config above.

**Comment by dewi-ny-je** [comment]
It's untested. As soon as I get mine I'll test it.

**Comment by mhendriks** [comment]
I am curious , any test results?

**Comment by dewi-ny-je** [comment]
I installed it but I'm using almost only the total counter, so given the number of projects I have in the queue the priority for improving the realtime flow indicator is low and I haven't touched it. In fact, I still have to hot-glue the white holder to ensure reliable readings, which comes first.

**Comment by dewi-ny-je** [comment]
Given that now AI exists, here it is.


```yaml
substitutions:
  device_name: waterlezer
  device_description: Water meter sensor 
  version: "v26.02.01"

esphome:
  name: ${device_name}
  comment: "${device_description}" 
  name_add_mac_suffix: false
  platformio_options:
    upload_speed: 1500000
  project:
    name: smartstuff.waterlezer
    version: ${version}
  on_boot:
    priority: -100
    then:
      - pulse_meter.set_total_pulses:
          id: watermeter_pulse
          value: !lambda "return id(totalWaterUsage);"

esp8266:
  board: esp12e
  restore_from_flash: true

status_led:
  pin:
    number: 2
    inverted: true

dashboard_import:
  package_import_url: github://mhendriks/esphome-p1/waterlezer.yaml

wifi:
  min_auth_mode: WPA2
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True
  ap:
    ssid: ${device_name}

web_server:
captive_portal:

logger:
  level: INFO

ota:
  platform: esphome

safe_mode:
  reboot_timeout: 10min
  num_attempts: 5

api:
  encryption:
    key: xxx
  actions:
    - action: set_water_reading
      variables:
        meter_value: int
      then:
        - globals.set:
            id: totalWaterUsage
            value: !lambda "return meter_value;"
        - pulse_meter.set_total_pulses:
            id: watermeter_pulse
            value: !lambda "return meter_value;"

globals:
  - id: totalWaterUsage
    type: int
    restore_value: true
    initial_value: '0'

button:  
  - platform: restart
    name: "_Restart device"
  - platform: factory_reset
    name: "_Restart with Factory Default Settings"
  - platform: template
    name: "_Reset - Total Water Counter"
    id: button_reset_total
    on_press:
      - globals.set:
          id: totalWaterUsage
          value: "0"
      - pulse_meter.set_total_pulses:
          id: watermeter_pulse
          value: 0

sensor:
  - platform: pulse_meter
    pin: 
      number: 5
      inverted: true          # rising edge on an inverted pin == falling edge
      mode:
        input: true
        pullup: true
    id: watermeter_pulse
    name: "Watermeter pulse"
    unit_of_measurement: 'L/min'
    accuracy_decimals: 0
    state_class: measurement
    icon: mdi:water-pump
    internal_filter: 100ms
    internal_filter_mode: PULSE
    timeout: 5min
    total:
      name: "Watermeter total"
      id: watermeter_total
      unit_of_measurement: 'L'
      device_class: water
      state_class: total_increasing
      accuracy_decimals: 0
      icon: mdi:water
      on_value:
        then:
          - globals.set:
              id: totalWaterUsage
              value: !lambda "return (int) x;"

  - platform: adc
    pin: VCC
    name: "VCC Voltage"
    accuracy_decimals: 2
    device_class: "voltage"
    state_class: "measurement"
    entity_category: diagnostic
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "Uptime"

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP-adres"
      icon: mdi:ip-network
    ssid:
      name: "Netwerk"
      icon: mdi:access-point-network
    mac_address:
      name: "Mac-adres"
      icon: mdi:folder-key-network-outline
  - platform: template
    name: "Config Version"
    icon: "mdi:label-outline"
    update_interval: 6h
    lambda: return {"${version}"};
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
```

I also asked which one is the best choice.

> Yes, for a household water meter it's the better fit, and the reason is pulse rate.
> 
> A typical meter gives 1 pulse per litre. A running tap is around 6 L/min, so you get one pulse every 10 seconds. A shower might be 9 L/min. Even a bath filling flat out rarely exceeds 30 L/min, or one pulse every 2 seconds. That's a sub-1 Hz signal.
> 
> `pulse_counter` counts edges inside a fixed window and reports the average. With your original 1-second window and one pulse per 10 seconds, nine readings out of ten are 0 L/min and the tenth is 60 L/min. The average over a minute is right, but every individual reading is wrong, and Home Assistant's graphs and any automation reading the current state see nonsense. You'd have to push `update_interval` up to 30–60s to get a believable number, and then you've lost all responsiveness.
> 
> `pulse_meter` measures the time between two consecutive pulses and derives the rate from that. One pulse per 10 seconds becomes a clean 6 L/min. This is the case the component was written for — low-frequency utility metering is its stated purpose.
> 
> Where `pulse_counter` would still win is high pulse rates: something like a wind sensor or a flow turbine putting out hundreds of hertz, where interval timing gets noisy and you actually want the averaging. That isn't your situation.
> 
> Two things to check regardless of which component you use:
> 
> **Pulses per litre.** Both my converted config and your original assume 1 pulse = 1 L. If your meter emits a pulse per 0.5 L or per 10 L, the rate and the total are both scaled wrong. Fix it with a `filters: - multiply: 0.5` on the rate sensor and the same on `total:`, rather than fudging the unit label.
> 
> **Timeout behaviour.** `pulse_meter` holds the last computed rate until `timeout` expires, so after you shut the tap off, HA will keep showing the old flow rate for up to 5 minutes. Volume is unaffected, since the total comes from counted pulses rather than integrated rate, but the display lags. Dropping `timeout` to `2min` makes it feel more responsive. Don't drop it much below that or a slow trickle will flap between a rate and zero.
> 
> One thing worth setting expectations on: don't use the rate sensor for leak detection. A dripping joint at 1 L/hour produces one pulse an hour, which any timeout you'd want for normal use will have long since zeroed. Detect that from the total instead — a `total_increasing` sensor that creeps upward during hours when nobody's home is the signal you want.

I will report issues in the next days, if any, or I will confirm in few days it works fine, so you can update your YAML.
