### ISSUE TITLE
malformed checksum

### ISSUE THREAD

**Issue by ronajon** [mhendriks/esphome-p1#3]
since a couple of days the p1 dongle does send/show dsmr data anymore. 
after successful installing, it gives errors

```
[16:26:20][D][api:102]: Accepted 192.168.110.105
[16:26:20][D][api.connection:920]: Home Assistant 2023.3.3 (192.168.110.105): Connected successfully
[16:26:21][E][dsmr:265]:  "0  0

                    ^

Incomplete or malformed checksum
[16:26:23][E][dsmr:265]:  "0 , 8

                    ^

Incomplete or malformed checksum
[16:26:26][E][dsmr:265]:  ("0  0

                    ^

Incomplete or malformed checksum
[16:26:29][E][dsmr:265]:  20  0

                             ^

Incomplete or malformed checksum
``` 

my config
```
substitutions:
  device_name: p1-dongle
  device_description: "P1 module to read your smart meter"
  friendly_name: P1 Dongle
  ip_address: aaa.bbb.ccc.ddd
  
esphome:
  name: ${device_name}
  comment: "${device_description}" 
  name_add_mac_suffix: false
  
  project:
    name: smartstuff.slimmelezer
    version: "v22.12.1"
  
esp8266:
  board: esp12e
  restore_from_flash: true

status_led:
  pin:
    number: 2
    inverted: true

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: false
  use_address: ${ip_address}
  domain: .local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${device_name} hs
    password: !secret password

dashboard_import:
  package_import_url: github://mhendriks/esphome-p1/p1-dongle.yaml
  
captive_portal:

web_server:
  
# Enable logging
logger:
  level: debug
  esp8266_store_log_strings_in_flash: False
  baud_rate: 0

uart:
  baud_rate: 115200
  rx_pin: 13
  rx_buffer_size: 1700
  
dsmr:
  id: dsmr_instance
  receive_timeout: 200ms
  max_telegram_length: 1700

button:  
  - platform: restart
    name: "_Restart device"
  - platform: factory_reset
    name: "_Restart with Factory Default Settings"
  
sensor:
  - platform: dsmr
#    energy_delivered_lux:
#      name: "Energy Consumed Luxembourg"
#      state_class: total_increasing
    energy_delivered_tariff1:
      name: "Energy Consumed Tariff 1"
      state_class: total_increasing
    energy_delivered_tariff2:
      name: "Energy Consumed Tariff 2"
      state_class: total_increasing
#    energy_returned_lux:
#      name: "Energy Produced Luxembourg"
#      state_class: total_increasing
    energy_returned_tariff1:
      name: "Energy Produced Tariff 1"
      state_class: total_increasing
    energy_returned_tariff2:
      name: "Energy Produced Tariff 2"
      state_class: total_increasing
    power_delivered:
      name: "Power Consumed"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned:
      name: "Power Produced"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    electricity_failures:
      name: "Electricity Failures"
      icon: mdi:alert
    electricity_long_failures:
      name: "Long Electricity Failures"
      icon: mdi:alert
    voltage_l1:
      name: "Voltage Phase 1"
    voltage_l2:
      name: "Voltage Phase 2"
    voltage_l3:
      name: "Voltage Phase 3"
    current_l1:
      name: "Current Phase 1"
    current_l2:
      name: "Current Phase 2"
    current_l3:
      name: "Current Phase 3"
    power_delivered_l1:
      name: "Power Consumed Phase 1"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_delivered_l2:
      name: "Power Consumed Phase 2"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_delivered_l3:
      name: "Power Consumed Phase 3"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l1:
      name: "Power Produced Phase 1"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l2:
      name: "Power Produced Phase 2"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    power_returned_l3:
      name: "Power Produced Phase 3"
      unit_of_measurement: "W"
      state_class: "measurement"
      accuracy_decimals: 0
      filters:
        - multiply: 1000
    gas_delivered:
      name: "Gas Consumed"
      state_class: total_increasing
    gas_delivered_be:
      name: "Gas Consumed Belgium"
      state_class: total_increasing
  - platform: uptime
    name: "Uptime"
  - platform: wifi_signal
    name: "Wi-Fi Signal"
    update_interval: 60s
      
text_sensor:
  - platform: dsmr
    identification:
      name: "DSMR Identification"
    p1_version:
      name: "DSMR Version"
    p1_version_be:
      name: "DSMR Version Belgium"
  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Wi-Fi SSID"
    bssid:
      name: "Wi-Fi BSSID"
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: true
```
