### ISSUE TITLE
Gas usage reported as Water usage

### ISSUE THREAD

**Issue by tony-p** [mhendriks/esphome-p1#6]
I have the p1 dongle pro attached to an ESMR 5 meter (NL) and the gas delivered reports NA, and the water usage reports as the gas level. (I'm pretty new to HA and ESPhome) but as far as I can gather I can't just switch these values in the yaml file and the energy reporting on HA doesn't let me select the water sensor as gas sensor.

**Comment by mhendriks** [comment]
Hi Tony, is it possible to share the yaml (or gas/water parts)?

**Comment by tony-p** [comment]
Is just reference standard one from the repo (references it)

```yaml
substitutions:
  name: p1-dongle-pro
packages:
  smartstuff.p1_dongle_pro: github://mhendriks/esphome-p1/p1-dongle-pro.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: ...


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

```
