### ISSUE TITLE
S0 Dongle resets daily usage at 01.00hrs

### ISSUE THREAD

**Issue by Nijhuis** [mhendriks/esphome-p1#7]
I have three s0 dongles running in my home, they all reset the daily usage at 01.00hrs instead of 00.00hrs. Time of HomeAssistant and of the ux server running HomeAssistant is correct. I am on Amsterdam/Europe timezone.

**Comment by mhendriks** [comment]
This is strange. 
quick look result in : https://github.com/esphome/issues/issues/3736
"add tz in ESPHome config".

could be fixed by adding the below:

```
time:
  - platform: sntp

or

time:
  - platform: homeassistant
    id: homeassistant_time  

```
